version: '3.8'

services:
  crypto-bot:
    build: .
    container_name: crypto-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./crypto_bot.env:/app/crypto_bot.env:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.coingecko.com/api/v3/ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
