#!/bin/bash

# Quick Google Cloud Setup for Crypto Bot
# This script provides step-by-step instructions for manual setup

echo "🚀 Google Cloud Crypto Bot Setup"
echo "================================"
echo ""
echo "📋 Manual Setup Steps:"
echo ""
echo "1. 🌐 Open Google Cloud Console:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. 🔐 Login to your Google account"
echo ""
echo "3. 📁 Create a new project:"
echo "   - Click 'Select a project' → 'New Project'"
echo "   - Name: 'crypto-bot-project'"
echo "   - Click 'Create'"
echo ""
echo "4. 💳 Enable billing (if not already enabled):"
echo "   - Go to 'Billing' in the left menu"
echo "   - Link a payment method (free tier available)"
echo ""
echo "5. 🖥️ Create a VM instance:"
echo "   - Go to 'Compute Engine' → 'VM instances'"
echo "   - Click 'Create Instance'"
echo "   - Name: 'crypto-bot-vm'"
echo "   - Region: 'us-central1' (Iowa - cheapest)"
echo "   - Machine type: 'e2-micro' (free tier)"
echo "   - Boot disk: 'Ubuntu 22.04 LTS'"
echo "   - Click 'Create'"
echo ""
echo "6. 🔑 SSH into your VM:"
echo "   - Click 'SSH' button next to your VM"
echo "   - This opens a browser-based terminal"
echo ""
echo "7. 📥 Upload your bot files:"
echo "   - In the SSH terminal, run:"
echo "   git clone https://github.com/your-username/crypto-bot.git"
echo "   # OR upload files manually"
echo ""
echo "8. 🐍 Install Python and dependencies:"
echo "   sudo apt update"
echo "   sudo apt install python3-pip python3-venv git -y"
echo "   python3 -m venv crypto_bot_env"
echo "   source crypto_bot_env/bin/activate"
echo "   pip install -r requirements_crypto_bot.txt"
echo ""
echo "9. 🔧 Configure your bot:"
echo "   nano crypto_bot.env"
echo "   # Add your Telegram bot token"
echo ""
echo "10. 🚀 Run your bot:"
echo "    python top100_crypto_bot.py"
echo ""
echo "11. 🔄 Keep it running:"
echo "    # Install screen to keep it running:"
echo "    sudo apt install screen -y"
echo "    screen -S crypto-bot"
echo "    python top100_crypto_bot.py"
echo "    # Press Ctrl+A, then D to detach"
echo ""
echo "✅ Your bot will be running 24/7 on Google Cloud!"
echo ""
echo "💰 Cost: ~$6/month (or free for 12 months with free tier)"
echo "🌍 Your bot will be accessible worldwide!"
